version: '3.9'
services:
  pg:
    image: postgres:13
    user: '1000:1000'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pg_hba_editor_db
    volumes:
        - ./local_pgdata/:/var/lib/postgresql/data

